# Generated by Django 3.0 on 2020-01-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='THIS IS A TEST DESCRIPTION REST IS BLA BLA BLAAAAAA kasjbdaksf aksjbdflaksdnakjsvdfakjns cda jbalsdknalsk asdlkans sbdlaks ja '),
            preserve_default=False,
        ),
    ]
